name: Black Code Formatter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Check code formatting with Black
        run: |
          black --check hyperdt tests
      - name: Check import formatting with isort
        run: |
          isort --check --profile black hyperdt tests
      - name: Format code with Black if check fails
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          black hyperdt tests
          isort --profile black hyperdt tests
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add hyperdt tests
          git commit -m "Auto-format code with Black and isort" || echo "No changes to commit"
          git push